[package]
name = "midi-buzzer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
midly = "0.5"
serde = { version = "1", features = ["derive"] }
tract-onnx = "0.21"
symphonia = { version = "0.5", default-features = false, features = [
    "mp3",
    "wav",
    "flac",
    "ogg",
    "vorbis",
    "aac",
    "isomp4",
    "pcm",
] }
rubato = "0.16"
