/*
 * buzzer_player.h - 通用 STM32 无源蜂鸣器播放器
 * Generated by MIDI Buzzer Studio
 *
 * 可移植性：
 *   仅依赖 HAL 库通用宏 __HAL_TIM_SET_AUTORELOAD / __HAL_TIM_SET_COMPARE，
 *   适用于全系列 STM32（F0/F1/F4/F7/G0/G4/H7...）的任意 PWM 定时器通道。
 *
 * 用法（在 CubeMX 中把某个定时器通道配为 PWM Generation 后）：
 *   BuzzerPlayer_t buzzer;
 *   BuzzerPlayer_Init(&buzzer, &htim3, TIM_CHANNEL_1, 1000000); // 1MHz 计数时钟
 *   Play_YourSong(&buzzer);
 */
#ifndef BUZZER_PLAYER_H
#define BUZZER_PLAYER_H

#include "main.h"   /* CubeMX 工程均有此文件，内部包含对应系列的 stm32xx_hal.h */

#ifdef __cplusplus
extern "C" {
#endif

/* 单个音符：frequency 单位 Hz（0 表示休止符），duration_ms 单位 ms，volume 0~100 */
typedef struct {
    float    frequency;
    uint32_t duration_ms;
    uint8_t  volume;
} BuzzerNote_t;

typedef struct {
    TIM_HandleTypeDef *htim;          /* PWM 定时器句柄，如 &htim3 */
    uint32_t           channel;       /* TIM_CHANNEL_1 ~ TIM_CHANNEL_4 */
    uint32_t           timer_clock_hz;/* 定时器计数时钟（PSC 分频后），如 1000000 = 1MHz */
} BuzzerPlayer_t;

void BuzzerPlayer_Init(BuzzerPlayer_t *player, TIM_HandleTypeDef *htim, uint32_t channel, uint32_t timer_clock_hz);
void BuzzerPlayer_Play(BuzzerPlayer_t *player, const BuzzerNote_t *notes, uint32_t count, uint8_t master_volume, uint32_t gap_ms);
void BuzzerPlayer_Stop(BuzzerPlayer_t *player);

#ifdef __cplusplus
}
#endif

#endif /* BUZZER_PLAYER_H */
