use crate::midi::SongNote;

/// 转为合法 C 标识符：非字母数字换 `_`，数字开头补 `_`，空则回退 "Song"
pub fn sanitize_ident(name: &str) -> String {
    let mut ident: String = name
        .trim()
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    ident = ident.trim_matches('_').to_string();
    if ident.is_empty() {
        ident = "Song".to_string();
    }
    if ident.chars().next().unwrap().is_ascii_digit() {
        ident = format!("_{ident}");
    }
    ident
}

pub fn generate_song_h(ident: &str) -> String {
    let guard = format!("{}_H", ident.to_uppercase());
    format!(
        "/* Generated by MIDI Buzzer Studio */\n\
         #ifndef {guard}\n\
         #define {guard}\n\
         \n\
         #include \"buzzer_player.h\"\n\
         \n\
         void Play_{ident}(BuzzerPlayer_t *player);\n\
         \n\
         #endif /* {guard} */\n"
    )
}

pub fn generate_song_c(
    ident: &str,
    notes: &[SongNote],
    master_volume: u8,
    gap_ms: u32,
) -> String {
    let mut rows = String::new();
    for n in notes {
        rows.push_str(&format!(
            "    {{ {:9.3}f, {:>5}u, {:>3}u }}, /* {} */\n",
            n.frequency, n.duration_ms, n.volume, n.comment
        ));
    }
    format!(
        "/* Generated by MIDI Buzzer Studio */\n\
         #include \"{ident}.h\"\n\
         \n\
         #define SONG_MASTER_VOLUME {master_volume}u\n\
         #define SONG_GAP_MS        {gap_ms}u\n\
         \n\
         static const BuzzerNote_t song_notes[] = {{\n\
         {rows}}};\
         \n\
         #define SONG_NOTE_COUNT ((uint32_t)(sizeof(song_notes) / sizeof(song_notes[0])))\n\
         \n\
         void Play_{ident}(BuzzerPlayer_t *player)\n\
         {{\n\
         \x20   BuzzerPlayer_Play(player, song_notes, SONG_NOTE_COUNT, SONG_MASTER_VOLUME, SONG_GAP_MS);\n\
         }}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_sanitized() {
        assert_eq!(sanitize_ident("Haruhikage-CRYCHIC"), "Haruhikage_CRYCHIC");
        assert_eq!(sanitize_ident("  春日影  "), "Song");
        assert_eq!(sanitize_ident("123abc"), "_123abc");
        assert_eq!(sanitize_ident("my song 2"), "my_song_2");
    }

    #[test]
    fn song_c_shape() {
        let notes = vec![
            SongNote {
                frequency: 523.251,
                duration_ms: 309,
                volume: 78,
                comment: "C5".into(),
            },
            SongNote {
                frequency: 0.0,
                duration_ms: 120,
                volume: 0,
                comment: "REST".into(),
            },
        ];
        let c = generate_song_c("Test", &notes, 100, 25);
        assert!(c.contains("#include \"Test.h\""));
        assert!(c.contains("{   523.251f,   309u,  78u }, /* C5 */"));
        assert!(c.contains("/* REST */"));
        assert!(c.contains("BuzzerPlayer_Play(player, song_notes, SONG_NOTE_COUNT, SONG_MASTER_VOLUME, SONG_GAP_MS);"));
        assert!(c.contains("#define SONG_MASTER_VOLUME 100u"));

        let h = generate_song_h("Test");
        assert!(h.contains("#ifndef TEST_H"));
        assert!(h.contains("void Play_Test(BuzzerPlayer_t *player);"));
    }
}
