pub const PLAYER_H: &str = r#"/*
 * buzzer_player.h - 通用 STM32 无源蜂鸣器播放器
 * Generated by MIDI Buzzer Studio
 *
 * 可移植性：
 *   仅依赖 HAL 库通用宏 __HAL_TIM_SET_AUTORELOAD / __HAL_TIM_SET_COMPARE，
 *   适用于全系列 STM32（F0/F1/F4/F7/G0/G4/H7...）的任意 PWM 定时器通道。
 *
 * 用法（在 CubeMX 中把某个定时器通道配为 PWM Generation 后）：
 *   BuzzerPlayer_t buzzer;
 *   BuzzerPlayer_Init(&buzzer, &htim3, TIM_CHANNEL_1, 1000000); // 1MHz 计数时钟
 *   Play_YourSong(&buzzer);
 */
#ifndef BUZZER_PLAYER_H
#define BUZZER_PLAYER_H

#include "main.h"   /* CubeMX 工程均有此文件，内部包含对应系列的 stm32xx_hal.h */

#ifdef __cplusplus
extern "C" {
#endif

/* 单个音符：frequency 单位 Hz（0 表示休止符），duration_ms 单位 ms，volume 0~100 */
typedef struct {
    float    frequency;
    uint32_t duration_ms;
    uint8_t  volume;
} BuzzerNote_t;

typedef struct {
    TIM_HandleTypeDef *htim;          /* PWM 定时器句柄，如 &htim3 */
    uint32_t           channel;       /* TIM_CHANNEL_1 ~ TIM_CHANNEL_4 */
    uint32_t           timer_clock_hz;/* 定时器计数时钟（PSC 分频后），如 1000000 = 1MHz */
} BuzzerPlayer_t;

void BuzzerPlayer_Init(BuzzerPlayer_t *player, TIM_HandleTypeDef *htim, uint32_t channel, uint32_t timer_clock_hz);
void BuzzerPlayer_Play(BuzzerPlayer_t *player, const BuzzerNote_t *notes, uint32_t count, uint8_t master_volume, uint32_t gap_ms);
void BuzzerPlayer_Stop(BuzzerPlayer_t *player);

#ifdef __cplusplus
}
#endif

#endif /* BUZZER_PLAYER_H */
"#;

pub const PLAYER_C: &str = r#"/* Generated by MIDI Buzzer Studio */
#include "buzzer_player.h"

/* 延时函数：默认 HAL_Delay。
 * 使用 RTOS 时，在包含本文件前（或编译选项中）定义：
 *   #define BUZZER_DELAY_MS(ms) osDelay(ms)
 */
#ifndef BUZZER_DELAY_MS
#define BUZZER_DELAY_MS(ms) HAL_Delay(ms)
#endif

void BuzzerPlayer_Init(BuzzerPlayer_t *player, TIM_HandleTypeDef *htim, uint32_t channel, uint32_t timer_clock_hz)
{
    player->htim = htim;
    player->channel = channel;
    player->timer_clock_hz = (timer_clock_hz == 0u) ? 1000000u : timer_clock_hz;
    HAL_TIM_PWM_Start(htim, channel);
    __HAL_TIM_SET_COMPARE(htim, channel, 0u);
}

void BuzzerPlayer_Stop(BuzzerPlayer_t *player)
{
    __HAL_TIM_SET_COMPARE(player->htim, player->channel, 0u);
}

static void Buzzer_Tone(BuzzerPlayer_t *player, float frequency, uint8_t volume)
{
    if (frequency <= 0.0f || volume == 0u) {
        __HAL_TIM_SET_COMPARE(player->htim, player->channel, 0u);
        return;
    }
    uint32_t arr = (uint32_t)((float)player->timer_clock_hz / frequency);
    if (arr < 2u)     arr = 2u;
    if (arr > 65535u) arr = 65535u;   /* 兼容纯 16 位定时器 */
    __HAL_TIM_SET_AUTORELOAD(player->htim, arr);
    /* 50% 占空比为满音量，按音量百分比缩放 */
    __HAL_TIM_SET_COMPARE(player->htim, player->channel, (arr / 2u) * volume / 100u);
    __HAL_TIM_SET_COUNTER(player->htim, 0u);
}

void BuzzerPlayer_Play(BuzzerPlayer_t *player, const BuzzerNote_t *notes, uint32_t count, uint8_t master_volume, uint32_t gap_ms)
{
    for (uint32_t i = 0u; i < count; i++) {
        const BuzzerNote_t *note = &notes[i];
        uint32_t volume = (uint32_t)note->volume * master_volume / 100u;
        if (volume > 100u) volume = 100u;

        Buzzer_Tone(player, note->frequency, (uint8_t)volume);

        if (note->frequency > 0.0f && volume > 0u && gap_ms > 0u && note->duration_ms > gap_ms) {
            /* 音符尾部留出 gap 静音，避免连音 */
            BUZZER_DELAY_MS(note->duration_ms - gap_ms);
            __HAL_TIM_SET_COMPARE(player->htim, player->channel, 0u);
            BUZZER_DELAY_MS(gap_ms);
        } else {
            BUZZER_DELAY_MS(note->duration_ms);
        }
    }
    __HAL_TIM_SET_COMPARE(player->htim, player->channel, 0u);
}
"#;
